package com.example.webhelpdesksystem.mapper;

import com.example.webhelpdesksystem.dto.EmployeeDTO;
import com.example.webhelpdesksystem.model.Employee;
import com.example.webhelpdesksystem.model.Ticket;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.factory.Mappers;
import org.springframework.context.annotation.Configuration;
import com.example.webhelpdesksystem.dto.TicketDTO;

import java.util.List;

@Configuration
@Mapper
public interface TicketMapper {

    // reference variable to the autogenerated implementation
    TicketMapper INSTANCE = Mappers.getMapper(TicketMapper.class);

    // entity to dto
    TicketDTO ticketToDTO(Ticket ticket);

    // dto to entity
    Ticket dtoToTicket(TicketDTO ticketDTO);

    // list of ticket to list of dto
    List<TicketDTO> listTicketsToDTO (List<Ticket> ticketList);

    // list of employee to list of dto
    List<EmployeeDTO> listEmployeeToDTO(List<Employee> employeeList);

    // update ticket details from old to new
    @Mapping(target = "ticket_number", ignore = true)
    void updateTicketDetails(TicketDTO ticketDTO, @MappingTarget Ticket ticket);


}
